### PR TITLE
Corrected clear behavior as per bgentry/flipper-activerecord#4

### LINKED ISSUE #4: Adapter#clear should only clear gate values
It is documented as such, but I did not have a clear expectation in the test (since added here https://github.com/jnunemaker/flipper/pull/106). [This line](https://github.com/bgentry/flipper-activerecord/blob/cbdc8ab4ec57799343a6c8a9c2192f6bd87bc3d8/lib/flipper/adapters/activerecord.rb#L38) should only [clear the gates like this](https://github.com/jnunemaker/flipper/blob/4c6a9978940e0f7b097e51df153c4cac49f141c8/lib/flipper/adapters/active_record.rb#L66), not the entire feature, or you end up with behavior like this https://github.com/jnunemaker/flipper/issues/104 in the flipper UI.

### PR DESCRIPTION
**Pull request by trinode**
Fixes #4

### CODE REVIEW

**Comment by bgentry** [comment]
@trinode thanks! have you verified this passes the flipper test suite?

**Comment by trinode** [comment]
@bgentry it does now :)

**Comment by bgentry** [comment]
@trinode awesome. Do you mind squashing these together into a single commit before I merge it?

**Comment by trinode** [comment]
@bgentry done :) are you likely to do a release to rubygems soon?

**Comment by bgentry** [comment]
@trinode done! v0.1.3 just released. Thanks again for the fix :v:

**Pull request merged**
